OP_ADD = "ADD"
OP_ASSERT_EQ = "ASSERT_EQ"
OP_CLAIM = "CLAIM"
OP_JZ = "JZ"
OP_LT = "LT"
OP_MOD = "MOD"
OP_MUL = "MUL"
OP_READ_PRIV = "READ_PRIV"
OP_READ_PUB = "READ_PUB"
OP_SET = "SET"
OP_SUB = "SUB"

FUNC_CLAIM = "claim"
FUNC_CONST = "const"
FUNC_PRIVATE = "private"
FUNC_PUBLIC = "public"
FUNC_RANGE = "range"

BOOL_ONE = "1"
ZERO_REGISTER = "r0"
U64_MAX = (1 << 64) - 1

FIRST_ALLOC_REG = 1
LAST_ALLOC_REG = 15
