[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "fib"
path = "src/fib.rs"

[[bin]]
name = "rsa_enc"
path = "src/rsa_enc.rs"

[[bin]]
name = "rsa_dec"
path = "src/rsa_dec.rs"

[[bin]]
name = "range_proof"
path = "src/range_proof.rs"

[dependencies]
risc0-zkvm = { version = "^3.0.5", default-features = false, features = ['std'] }
